require 'simplecov'
SimpleCov.start
require 'Minitest/autorun'
require 'Minitest/pride'
require 'pry'
require 'mocha/minitest'
require './lib/stat_tracker'
require './lib/games'
require './lib/game_teams'
require './lib/teams'
require './lib/games_repo'
require './lib/game_teams_repo'
require './lib/teams_repo'